language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t baaboo2u/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true baaboo2u/react-test npm test -- --coverage

after_success:
  - docker build -t baaboo2u/multi-client ./client
  - docker build -t baaboo2u/multi-nginx ./nginx
  - docker build -t baaboo2u/multi-server ./server
  - docker build -t baaboo2u/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"  --password-stdin
  # Take these images and push them to docker hub
  - docker push baaboo2u/multi-client
  - docker push baaboo2u/multi-nginx
  - docker push baaboo2u/multi-server
  - docker push baaboo2u/multi-worker
